name: Build project with Hugo
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./public    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Install Hugo
        run: |
            sudo apt-get update
            sudo apt-get install -y software-properties-common
            sudo add-apt-repository -y ppa:longsleep/golang-backports
            sudo apt-get update
            sudo apt-get install -y hugo
  
      - name: Build Site with Hugo
        run: hugo
      
      - name: List output for current dir
        run: ls -l .

      - name: List output for debugging
        run: ls -l public

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
            args: deploy --only hosting
        env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

          
          